sul-dlss/dlme-transform

invoke.sh

Fixes #26
Note that associated IAMs must have the `s3:PutObjectAcl` action in:
```
aws iam get-user-policy --user-name myuser --policy-name mypolicy
```

Grant public-read to uploaded files

---

lib/csv_reader.rb

csv_reader uses delegation; explicitly require activesupport to get it

delegation requires activesupport

---

lib/cli.rb

StandardError is broader and encompases things like TypeError
Fixes #99

Rescue StandardError rather than RuntimeError

---

lib/translation_maps/french-types.yaml

Found some errors in the type field that were coming from the bnf data. While I was fixing them it made sense to break out the french type fields into a separate translation map instead of using default('image') to fix the problem.

add translation map for french types

---

lib/macros/iiif.rb

Refs https://github.com/sul-dlss/dlme-transform/issues/147
Fixes the require for IIIF manifests and then logs if the manifest is not found.

Update require for DLME utils and capture error

---

.github/pull_request_template.md

B/c "consul" shouldn't be mentioned in the context of DLME so I took it out of PR template
n/a

tweak PR template

---

Gemfile
Gemfile.lock

A recent bump to TrajectPlus 1.2.0 is causing errors when transforming data:
```
[ERROR] Error loading configuration file config/mods_config.rb:11
NoMethodError:undefined method `extended' for #<Traject::Indexer:0x0000564b796c1bd0>
Did you mean? extend
/usr/local/bundle/gems/traject-3.2.0/lib/traject/indexer.rb:231:in `rescue in block in load_config_file': ...
```
Once https://github.com/sul-dlss/traject_plus/issues/33 is closed, we can revert
this PR and/or update TrajectPlus again.
N/A

Pin TrajectPlus to 1.1.x

---

lib/dlme_json_schema.rb

When performing `docker run` on data formerly working without a hitch, there were errors like
```
The errors are: [#<Dry::Schema::Message text="is missing" path=[:cho_title] predicate=:key? input={}>, #<Dry::Schema::Message text="is missing" path=[:id] predicate=:key? input={}>, #<Dry::Schema::Message text="is missing" path=[:agg_data_provider] predicate=:key? input={}>, #<Dry::Schema::Message text="is missing" path=[:agg_provider] predicate=:key? input={}>]}
``` 
This fix avoids the errors.  Whether or not the desired validation is happening may need the help of @justinlittman eventually, but should not hold up this PR.
n/a

fix dlme_json_schema I hope

---

.gitignore
.rspec

So I could develop locally using the tools as I prefer:  pry for debugging and rspec in living color whenever possible.
n/a

Project config tweaks

---

Gemfile.lock

Use this instead of TrajectPlus 1.2.0 or 1.2.1, both of which contained breaking changes (in the context of our Traject configs in `dlme-traject`).
No.

Use TrajectPlus 1.2.2

---

Gemfile
Gemfile.lock

To use the correct version. (1.2.2 should have been 1.3.0.)
no

Bump TrajectPlus to 1.3.0

---

lib/macros/tei.rb

```
docker run --rm -e SKIP_FETCH_CONFIG=true -e SKIP_FETCH_DATA=true -v $(pwd)/.:/opt/traject -v $(pwd)/../dlme-traject:/opt/traject/config -v $(pwd)/../dlme-metadata:/opt/traject/data -v $(pwd)/output:/opt/traject/output suldlss/dlme-transform:latest penn
```
```
2019-09-26T20:41:40+00:00  INFO    Traject::Indexer with 1 processing threads, reader: TrajectPlus::XmlReader and writer: DlmeJsonResourceWriter
2019-09-26T20:41:40+00:00 ERROR Unexpected error on record <record #1 (data/penn/schoenberg/data/schoenberg-189.xml #1), output_id:penn_schoenberg-189>
while executing (to_field "agg_preview" at config/tei_config.rb:36)
Record: <?xml version="1.0" encoding="UTF-8"?>
<TEI xmlns="http://www.tei-c.org/ns/1.0">
... snip ...
</TEI>
Exception: NoMethodError: undefined method `gsub' for …
```

tei macro: penn_thumbnail url might be missing

---

lib/macros/aims.rb
lib/macros/harvard.rb
lib/macros/oai.rb
lib/macros/qnl.rb
lib/macros/srw.rb
lib/macros/tei.rb

Based on what @mjgiarlo did in sul-dlss/traject_plus/pull/34, this seems necessary (?).
n/a

mechanism changed for extending Traject macros

---

lib/macros/tei.rb

The method only works on the penn/openn data; the name will avoid future confusion. Accompanying changes in dlme-traject are on the way.
Not applicable

rename method to avoid future confusion

---

lib/dlme_json_schema.rb

```
[ERROR] Transform produced invalid data.
The errors are: [
#<Dry::Schema::Message text="is missing" path=[:agg_is_shown_by, :wr_has_service, 0, :service_id] predicate=:key? 
input={"service_conforms_to"=>["http://iiif.io/api/image/"], "service_id"=>"https://stacks.stanford.edu/image/iiif/cm881bj1960%2FW705_000001_300", "service_implements"=>"http://iiif.io/api/image/2/level2.json"}>, 
#<Dry::Schema::Message text="is missing" path=[:agg_is_shown_by, :wr_has_service, 0, :service_conforms_to] predicate=:key? 
input={"service_conforms_to"=>["http://iiif.io/api/image/"], "service_id"=>"https://stacks.stanford.edu/image/iiif/cm881bj1960%2FW705_000001_300", "service_implements"=>"http://iiif.io/api/image/2/level2.json"}>, 
#<Dry::Schema::Message text="is missing" path=[:agg_preview, …
```

dlme_json_schema: some fixes from upgrade to dry-schema gem

---

lib/macros/normalize.rb

Need to map an earliest date and latest date from separate incoming fields to a single `cho_date_norm` range. 
Not applicable

closes #215

---

lib/translation_maps/norm_languages_to_ar.yaml

Need Arabic language values for IR.
Not Applicable

add arabic language translation map

---

lib/dlme_json_schema.rb

The IR requires a field for the conversion of dates into hijri dates. Additional we need an array to capture the integer representation of all individual years within a range.
N/A

Add cho_date_norm and cho_date_hijri to schema

---

lib/translation_maps/norm_languages_to_ar.yaml

Update the Arabic language values in the translation map based on feedback from Qatar National Library
NA

Update Arabic language values in translation map, closes #174

---

lib/dlme_json_schema.rb

This is part of the work in #144 - the existing `dry-validation` syntax for `excluded_from?` does not actually raise the expected validation error. 
With this update I now see:
```
[ERROR] Transform produced invalid data.
The errors are: [#<Dry::Schema::Message text="must not be one of: NOT FOUND" path=[:cho_language, 0] predicate=:excluded_from? input="NOT FOUND">]}
```
N/A
A follow up PR will be made to improve the testing around this, however, this change is necessary now for the work that @jacobthill is doing.

Replaces the excluded from syntax so the error is raised

---

.circleci/config.yml
Gemfile
Gemfile.lock
lib/macros/date_parsing.rb
spec/lib/traject/macros/date_parsing_spec.rb

DLME date slider requires a Solr field with an Array of integer years for the whole range possible in a record.  This PR contains low hanging fruit for parsing out integer dates (and ranges) from strings using 2 existing gems, which will enable appropriate values for the date slider Solr field for about 8 collections.
These methods may be modified in the future to accommodate more data, and may not be relying on unmaintained gems after that.
Note that yes, it is possible to test our lambdas (and we should!)
n/a

add date_parsing macros

---

.circleci/config.yml
.gitignore

I added the env var in trying to debug why codeclimate wasn't showing test coverage.  I subsequently realized it was because the tests never run on master branch, and code climate only tracks coverage for master branch.
A PR to address the root cause is coming from Aaron separately.
n/a

Tweak circleci config

---

.circleci/config.yml

In order to report coverage on tests, the tests must be run against master.
N/A

Run tests on master to allow for code coverage report

---

lib/macros/normalize_type.rb

Refactor the normalize type code that is repeated in almost every config.
NA

refactor normalize type, closes #144

---

lib/adjust_cardinality.rb
lib/dlme_json_schema.rb
lib/macros/dlme.rb

Need to retrieve the newly added Arabic values for country and data provider from metadata_mapping.json. Changes to configs forthcoming.
Yes: https://github.com/sul-dlss/dlme/pull/590

retrieve Arabic country and provider values from metadata_mapping.json

---

Gemfile
Gemfile.lock
lib/macros/date_parsing.rb

to use the narrowly focused parse_date gem instead of the broader mods processing gem for date parsing.  (Eventually stanford-mods will use parse_date as well).
n/a

use parse_date gem instead of stanford-mods

---

lib/adjust_cardinality.rb
lib/macros/dlme.rb

Fixes #255
These fields do not need to be flattened; they are hashes. Flattening them produces an array of arrays, which breaks validation for language-aware fields.
Also:
* Remove dead code: `Macros::DLME` is using the `TrajectPlus` implementation of `from_settings` so the overridden implementation is never used. Remove it to reduce confusion.
nope.

Remove provider-related fields from cardinality adjuster

---

lib/cli.rb
lib/dlme_json_resource_writer.rb
lib/macros/content_dm.rb
lib/macros/dlme_marc.rb
lib/record_counter.rb
lib/transformer.rb
spec/lib/cli_spec.rb
spec/lib/traject/macros/date_parsing_spec.rb
spec/lib/traject/macros/dlme_spec.rb
spec/lib/traject/macros/met_spec.rb
spec/lib/traject/macros/post_process_spec.rb
spec/spec_helper.rb

This fixes an issue we have missed thus far w/ the `singleton` library not being required anywhere. 
The changes in this branch concentrate most requires for the gem into `lib/cli.rb` since it is the only entrypoint into the gem at this point. We require traject and traject_plus there so we do not need to require it higgledy-piggledy throughout the codebase. We require `singleton` in the `RecordCounter` class since it is only used in that one context. And we require `cli` in the specs so that the test suite uses the libraries *as required in the gem*, which helps surface errors specifying requirements.
no

Rejigger how requires are used

---

spec/lib/traject/macros/date_parsing_spec.rb

To clean up the date_parsing_spec to limit code duplication.
N/A

Refactor date_parsing_spec to DRY up indexer

---

Gemfile.lock
lib/macros/date_parsing.rb

In preparation for working with distinct "earliest_year" and "latest_year" values for date strings (e.g. for marc date ranges, among others)
n/a

upgrade to parse_date 0.2.0

---

traject_configs/marc_config.rb

penn/marc collection gets populated `cho_date_range_norm` field.   
I coded this, rather than leaving it for Jacob, because I wanted to make sure the new macro worked in situ, and because I wasn't sure if Jacob was already conversant with the specific byte parsing of MARC control fields.  (And frankly, who would want to be?)
Must have @jacobthill's approval after he has a chance to vet the resulting output.
n/a

penn/marc gets cho_date_range_norm

---

lib/macros/date_parsing.rb
spec/lib/traject/macros/date_parsing_spec.rb

This adds a macro that will take the range dates available in AUC (and other collections) as "yyyy; yyyy; yyyy;..." and return an array.
N/A

Add array_from_range macro

---

traject_configs/mods_config.rb

Without this include, the mods config fails.
N/A

Fix missing date_parsing include

---

traject_configs/michigan_config.rb

michigan collection gets populated `cho_date_range_norm` field.   
I coded this, rather than leaving it for Jacob, because I thought it might be tricky to get the correct bytes out of the 008 control field when it is parsed as XML.  (See PR #273 for the nifty facility traject provides for marc21 format).
Must have @jacobthill's approval after he has a chance to vet the resulting output.
Note that I ran this against the data, and a bunch of records went through, but it did halt on bad data (date range that was invalid).
n/a
closes #263

michigan gets cho_date_range_norm

---

.rubocop.yml

So rubocop will pass in the interim while we figure out our refactoring strategy for DateParsing macros.
n/a

add rubocop exception for module length for date_parsing

---

Gemfile
Gemfile.lock
README.md
Rakefile
config/metadata_mapping.json

Fixes #272
Includes:
* Add rake as a dependency
* Write a rake task that sorts the mapping config as requested
* Update documentation
* Commit results of running the rake task
To make it easier to make sense of the contents of the mapping config.
Yes.

Sort metadata mapping config alpha by first path

---

.circleci/config.yml
README.md
Rakefile

Consistency with other codebases. Less to remember.
Invoke the default rake task in the CI build.
Yes.

Add rake tasks for rubocop and rspec

---

lib/translation_maps/norm_has_type_to_ar.yaml

Add Arabic translation map for cho_has_type values, closes #155. An additional translation map may be necessary but this won't be clear until the mapping is underway.
n/a

add Arabic translation map for cho_has_type

---

traject_configs/marc_config.rb
traject_configs/met_config.rb
traject_configs/michigan_config.rb
traject_configs/numismatic_csv_config.rb
traject_configs/penn_museum_config.rb

This doc shows the status of current DLME collections for date range normalization
https://docs.google.com/spreadsheets/d/1U068CQlySkxiS2O5W70Uc4uc6t1DrqJGMcUO71CLokY/edit#gid=0
the following collections are supposedly "done" but were missing the config lines.
not sure why some of these lost their `cho_date_range_norm` stuff.  (perhaps a rebase conflict in some later PR, but it doesn't matter.  And `cho_date_range_norm` being missing probably impacted `cho_date_range_hijri` not being added, but again it doesn't matter.)
n/a

add missing date range fields we can currently process to traject configs

---

Gemfile
Gemfile.lock
lib/macros/date_parsing.rb
spec/lib/traject/macros/date_parsing_spec.rb
traject_configs/aims_config.rb
traject_configs/aub_common_config.rb
traject_configs/bnf_common_config.rb
traject_configs/cluster_config.rb
traject_configs/pppa_config.rb
traject_configs/princeton_movie_config.rb
traject_configs/princeton_mss_config.rb
traject_configs/qnl_config.rb

Closes #291
This PR shifts more of the date parsing burden to the parse_date gem.  With v0.3.1, a lot more date parsing functionality has been added to the parse_date gem since v0.2.0 (see https://github.com/sul-dlss/parse_date/releases and gem's README), much of it with DLME date string patterns in mind.
The parse_date gem gives us a range of years for anything timetwister could formerly do, plus a lot more patterns, such as BC years and centuries.
The commit messages explain what happened to the date_parsing macro code here.
In addition to the comment in DateParsing.parse_range macro referring to the parse_date gem git repo for more info, the spec for DateParsing.parse_range got a lot more examples as a means of some documentation.
This isn't really user facing enough to go in the …

Parse date 0.3.1

---

lib/macros/date_parsing.rb

To get rid of an annoying warning / possibly incorrect regex, and to have better comments for 2 of the date parsing macros.
n/a

Refactor tweaks

---

Gemfile.lock
lib/macros/date_parsing.rb
spec/lib/traject/macros/date_parsing_spec.rb
traject_configs/numismatic_csv_config.rb

Closes # 295.
With the fix for early dates in parse_date gem v0.3.2, there is no need to have a separate macro to parse date ranges for american numismatic society collection.
I ran the ANS collection with the fix and the data looked good, and no exceptions.
n/a

upgrade parse_date to v0.3.2 and use parse_date macro for numismatic collection

---

Gemfile.lock

Cambridge collections (#182) need the changes in v0.3.3 of parse_date gem
n/a

use parse_date v0.3.3

---

spec/lib/traject/macros/date_parsing_spec.rb

I figured out a more compact way to do xml tests for cambridge;  just wanted to make the spec smaller by applying same approach to fgdc date macro tests.
n/a

make fgdc xml date parsing specs more compact

---

Gemfile.lock

parse_date gem v0.3.4 handles 3 more parsing cases:
- yyy-yy  used by AU Cairo (e.g. `950-60`)
- yyy-yyyy used by Cambridge (e.g. `996–1021 CE`)
- yyyy to yyyy used by OPenn Free Library Philadelphia (e.g. `1500? to 1582`)
thus we will have better date range data for these cases. 
n/a

update parse_date to v0.3.4

---

lib/contracts/cho.rb
spec/lib/contracts/cho_spec.rb
traject_configs/stanford_mods_config.rb

Fixes sul-dlss/dlme#603
This bug was caused by having a Traject config (`stanford_mods_config.rb`) attempt to convert a field (`cho_title`) to the language hash which was already converted to the language hash in an earlier config (`mods_config.rb`). I added a validation that will fail the transformation if we do this again (a bug I introduced :D)
No.

Fix multilingual bug

---

.dockerignore

We were previously pulling configs from dlme-traject, we know need the base configs from this repository and with them ignored (and thus not built into the container) an error is thrown during the run:
```
[ERROR] No such file or directory @ rb_sysopen - /opt/traject/config/metadata_mapping.json
/opt/traject/lib/config_finder.rb:67:in `read': No such file or directory @ rb_sysopen - /opt/traject/config/metadata_mapping.json (Errno::ENOENT)
```
Note: this is blocking transforms from running in docker and AWS, but not if running manually.
N/A

Remove config from docker ignore as it is now required

---

traject_configs/bodleian_config.rb

closes #246 
Bodleian collections get date range fields populated
I looked at *all* the raw data for Bodleian, and there were only these 4 `date_statement` values that aren't converting to the intuitive correct values:
```
Arabic-12.json:  16th century, first half  # will get whole century (1500..1599)
Armenian-60.json:  1706/7  # will get 1706 only
Armenian-79.json:  1674/5  # will get 1674 only
Hebrew-790.json: Early 16th century # will get whole century (1500..1599) 
```
n/a

bodleian colls get date ranges

---

lib/macros/date_parsing.rb

The collection specific macros (and their support methods) are alpha ordered in this file;  penn_museum_date_range was ... not in line with its counterparts.  (OCD much, Naomi?)
n/a

date_parsing macros: move penn_museum_date_range higher in file

---

traject_configs/bodleian_config.rb

b/c i did a d'oh.  Bodleian needs access to the date macro code.
n/a

bodleian config gets date parsing macros

---

Gemfile.lock

Sakip needs the parse_date gem to fail quietly on non-parseable date values.  parse_date gem v0.4.0 provides this.
n/a

use parse_date v0.4.0

---

lib/macros/date_parsing.rb
spec/lib/traject/macros/date_parsing_spec.rb

`array_from_range` was a date parsing macro originally written for UAC collection.  UAC no longer uses it, and neither does anything else.  Closes #293, tho obliquely.
n/a

remove unused array_from_range date parsing macro

---

.rubocop.yml
lib/macros/date_parsing.rb
spec/lib/traject/macros/date_parsing_spec.rb

The date parsing macros file is on the long side;   
- I organized it into two sections, with comments:  
- first section is for general purpose macros, organized alphabetically.
- second section is for collection or metadata format specific macros, arranged alphabetically
- I changed `to_hijri` to be a helper method, not a class method, to be like all the other helper methods.
- I added a comment to the new `auc` macro
I made sure the number of specs (all passing) was the same for both master and this branch.  :-)
yes, if you count the comments added in the date_parsing file?  Otherwise n/a

Reorg date parsing file slightly

---

lib/macros/date_parsing.rb
spec/lib/traject/macros/date_parsing_spec.rb

Closes #320 
AUC collection wasn't converting cleanly;  the problem was a date field without a trailing semicolon:
```xml
2019-11-04T18:56:15+00:00 ERROR Unexpected error on record <record #1 (data/auc/p15795coll13/data/15.xml #1), output_id:oai:cdm15795.contentdm.oclc.org:p15795coll13/88>
while executing (to_field "cho_date_range_norm" at traject_configs/auc_config.rb:36)
Record: <?xml version="1.0"?>
<record xmlns="http://www.openarchives.org/OAI/2.0/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
snip
<dc:date>ca. 1970s</dc:date>
<dc:date>1970; 1971; 1972; 1973; 1974; 1975; 1976; 1977; 1978; 1979</dc:date>
```
This PR fixes the regular expression to allow a semicolon to be missing and fixes the final manipulation of the result array to use safe navigators.

Auc errors

---

lib/macros/date_parsing.rb

Fixes #321
I'd like @ndushay to review this before we merge it.
This unbreaks Sakip data transformation by making the following changes:
1. Concentrate year range normalization into a single method
2. Normalize ranges without mutation (avoiding the risk of chaining bang methods which can have unexpected consequences and which force us to do lots of nil-checking via safe navigation)
3. Add array compaction to normalization operations so we can deal with data like `[nil]`
4. Prefer `Array#empty?` over `Array#any?` since `[nil].any?` returns `false`, perhaps counter-intuitively
no

Normalize year ranges

---

traject_configs/sakip_sabanci_common_config.rb

Only the first date was being grabbed for cho_date. Need all dc:date values.
n/a

get all dc dates for cho_date field

---

lib/contracts/cho.rb
spec/lib/contracts/cho_spec.rb
traject_configs/aims_config.rb
traject_configs/aub_common_config.rb
traject_configs/auc_config.rb
traject_configs/bnf_common_config.rb
traject_configs/bodleian_config.rb
traject_configs/cambridge_config.rb
traject_configs/cluster_config.rb
traject_configs/csv_config.rb
traject_configs/fgdc_config.rb
traject_configs/harvard_ihp_config.rb
traject_configs/iiif_config.rb
traject_configs/marc_config.rb
traject_configs/met_config.rb
traject_configs/michigan_config.rb
traject_configs/mods_config.rb
traject_configs/numismatic_csv_config.rb
traject_configs/openn_common_config.rb
traject_configs/penn_museum_config.rb
traject_configs/pppa_config.rb
traject_configs/princeton_movie_config.rb
traject_configs/princeton_mss_config.rb
traject_configs/qnl_config.rb
traject_configs/sakip_sabanci_common_config.rb
traject_configs/yale_medical_config.rb

And use `cho_description` as the example.
Fixes #329

Add new rule for validating optional language-specific fields

---

Gemfile.lock

AU Cairo and some other collections have dates like '1990s' or '1938 - 1980s';  v0.4.1 of parse_date gem gets correct range from these patterns.
n/a

parse_date v0.4.1 get correct date ranges for yyy0s pattern

---

Gemfile.lock
traject_configs/bodleian_config.rb

See https://github.com/sul-dlss/parse_date/issues/33 -- at least 3 collections have some dates with yyyy-y pattern;  this will ensure we get correct range of years.
n/a

parse_date v0.4.2 get correct date ranges for yyyy-y pattern

---

config/metadata_mapping.json
lib/translation_maps/norm_has_type_to_ar.yaml
traject_configs/aub_aladab_config.rb
traject_configs/aub_common_config.rb
traject_configs/aub_postcards_config.rb

- Revise AUB mapping
- Add new collection specific config for postcards collection as the language values are different from the aladab collection
- Map new config to correct data set in metadata mapping file
- Add new field to cho_has_type translation map
n/a

Revise AUB mapping, fixes #346

---

lib/macros/dlme.rb
spec/lib/traject/macros/dlme_spec.rb

Closes #365.
Bug:  fields with transforms using `lang` macro were getting values like:
```
[{:language=>"en", :values=>[]}]
```
This fixes the bug.
n/a

lang macro only adds hash to accum. when it has a value

---

lib/contracts/cho.rb

Part of #383, this establishes the field to be used in configs as a hashed field in order to accommodate language tags.
N/A

Add cho_type_facet

---

config/metadata_mapping.json
lib/macros/dlme_marc.rb
traject_configs/README.md
traject_configs/marc_config.rb

In working on #371 (Michigan re-mappings), most of the configuration pertains to any MARC record, not to Michigan specifically.  In case there is more MARC data in our future, it seemed prudent to update marc_config.  This PR is only for the generic marc updates -- the Michigan specific PR will be separate, and is blocked by this PR.
Yes, README.

marc_config.rb updated substantially

---

lib/macros/each_record.rb
spec/lib/traject/macros/each_record_spec.rb
traject_configs/aims_config.rb
traject_configs/aub_aladab_config.rb
traject_configs/aub_postcards_config.rb
traject_configs/auc_common_config.rb
traject_configs/bnf_ideo_config.rb
traject_configs/bnf_ifao_config.rb
traject_configs/bodleian_config.rb
traject_configs/cambridge_config.rb
traject_configs/cluster_config.rb
traject_configs/fgdc_config.rb
traject_configs/harvard_ihp_config.rb
traject_configs/marc_config.rb
traject_configs/met_config.rb
traject_configs/michigan_config.rb
traject_configs/numismatic_csv_config.rb
traject_configs/openn_common_config.rb
traject_configs/penn_museum_config.rb
traject_configs/pppa_config.rb
traject_configs/princeton_movie_config.rb
traject_configs/princeton_mss_config.rb
traject_configs/qnl_config.rb
traject_configs/sakip_sabanci_common_config.rb
traject_configs/stanford_mods_config.rb

My first implementation of `add_cho_type_facet` macro was functional but somewhat tortured.  The goal of this PR is to make the code easier to understand and maintain.
n/a unless you count method comments.

refactor: greatly simplify add_cho_type_facet macro

---

lib/macros/each_record.rb
spec/lib/traject/macros/each_record_spec.rb

Fixes #390
To feed `blacklight-hierarchy` the values it expects.
no.

Return first value in addition to joined value for hierarchical facet values

---

lib/macros/normalize_language.rb
lib/translation_maps/language-errors.yaml
lib/translation_maps/languages.yaml
traject_configs/marc_config.rb

- Use normalize_language macro for language extraction
- Fix some mapping errors in Michigan language values
-n/a

Fix language mapping error in Michigan collection, fixes #351

---

Dockerfile
config/settings.yml
lib/contracts/cho.rb
lib/macros/timestamp.rb
lib/macros/version.rb
spec/lib/traject/macros/timestamp_spec.rb
spec/lib/traject/macros/version_spec.rb
traject_configs/aims_config.rb
traject_configs/aub_common_config.rb
traject_configs/auc_common_config.rb
traject_configs/bnf_common_config.rb
traject_configs/bodleian_config.rb
traject_configs/cambridge_config.rb
traject_configs/cluster_config.rb
traject_configs/csv_config.rb
traject_configs/fgdc_config.rb
traject_configs/harvard_ihp_config.rb
traject_configs/iiif_config.rb
traject_configs/marc_config.rb
traject_configs/met_config.rb
traject_configs/mods_config.rb
traject_configs/numismatic_csv_config.rb
traject_configs/openn_common_config.rb
traject_configs/penn_museum_config.rb
traject_configs/pppa_config.rb
traject_configs/princeton_movie_config.rb
traject_configs/princeton_mss_config.rb
traject_configs/qnl_config.rb
traject_configs/sakip_sabanci_common_config.rb
traject_configs/yale_medical_config.rb

In order to identify issues between transformation, indexing, and displaying, it will be very helpful to have a version tag and timestamp in the IR output.
This adds values like:
```
"transform_version":"ea0293c",
"transform_timestamp":"2019-11-20 10:47:07 -0800"
```
N/A

Add transform_version and transform_timestamp to IR

---

lib/macros/version.rb

Fixes #419 
This avoids raising an error in docker when git is not installed.

Move the git call in ENV.fetch to a block call

---

lib/contracts/cho.rb
lib/macros/each_record.rb
spec/lib/traject/macros/each_record_spec.rb

Fixes #413 
If the first value in the language hash is empty, raise an error.
N/A

Do not add empty strings to language hashed values

---

lib/macros/harvard.rb
traject_configs/harvard_ihp_config.rb

The harvard metadata was reharvested and changed in a way that broke it's existing configuration and thus caused the integration tests to fail. This fixes
- The xpath query into the nested data
- The namespace required for the thumbnail query
- Does not call the `.text` method on a `nil` value
Removing this from draft. There currently are almost no macro tests, so I'm proposing not blocking this for getting a test in and will follow up with a more comprehensive test PR.

Update Harvard mapping with proper xpath query

---

lib/dlme_json_resource_writer.rb

The default return inserted the value `true` into the json output when an error is logged. Which causes an error on item ingest.
N/A

Return nil when a an error is logged in the resource writer

---

lib/macros/cambridge.rb
traject_configs/cambridge_config.rb

Extract the ID from the URL, use the id to format the link and the iiif manifest URL.

Add formatted iiif manifest to cambridge based on ID

---

traject_configs/numismatic_csv_config.rb

The links to the ANS items include a manifest by switching "collection" to "search/manifest".

Add formatted iiif manifest to ans based on URL

---

config/metadata_mapping.json

- fix agg_provider and agg_data_provider mapping on BnF and Openn collections
- n/a

Fix metadata mapping for provider and data_provider fields

---

lib/translation_maps/turkish_has_type_to_en.yaml
traject_configs/sakip_sabanci_common_config.rb

There are many Turkish values in the type field that need to be mapped to subtypes (cho_has_type). It is unclear what some of the values mean so I mapped some and passed others through to view them in the application and determine if a new sub type label should be added. 
n/a

Test Turkish subtypes

---

traject_configs/numismatic_csv_config.rb

The iiif manifests were invalid and needed to be removed
n/a

Remove invalid iiif manifest urls from American Numismatic Society, closes https://github.com/sul-dlss/dlme/issues/795

---

traject_configs/shahre_farang_arabic_config.rb
traject_configs/shahre_farang_english_config.rb
traject_configs/shahre_farang_persian_config.rb

Some of the records have versions in multiple languages (e.g. a version in Persian and in English). The ids for the two are sometimes the same but we want to include both because there are differences at times in the metadata and the descriptive text. 
-n/a

Add language to id

---

traject_configs/auc_coptic_coll4_config.rb

Changes manuscripts to type 'Text' instead of type 'Image'
n/a

Fix type values for one AUC collection, closes #453

---

lib/macros/dlme.rb

The upstream `default` method is problematic as it appends a value to the array and doesn't replace an empty array with the default. This causes issues with our hashed language structure.

Add a default override macro that works

---

traject_configs/met_config.rb

- Consulted with colleague at Met who indicated that the provenance field was mapped incorrectly. This fixes that error.
n/a

Remove mismapped value

---

config/metadata_mapping.json
traject_configs/marc_config.rb
traject_configs/michigan_config.rb

- stop using marc config for michigan data because it was clashing with michigan config (see https://github.com/sul-dlss/dlme-transform/issues/494)
- stop using `marc_type_to_edm` macro for `cho_type` in `marc_config`; `cho_type` should not be normalized in any way
- move all michigan transformations to `michigan_config`
n/a

Untangle Michigan and Marc configs

---

traject_configs/loc_abdul_hamid_ii_books_config.rb
traject_configs/loc_greek_and_armenian_patriarchates_config.rb
traject_configs/loc_persian_config.rb

- Some iiif manifests didn't have canvases and needed to be removed
- Better approach for grabbing iiif manifests with canvases
n/a

update iiif manifests in LOC mapping

---

lib/translation_maps/norm_has_type_to_en.yaml
lib/translation_maps/norm_languages_to_en.yaml
lib/translation_maps/norm_types_to_en.yaml

Closes #535 
This change adds source language YML files for English so that Arabic translations can be managed in Transifex with QNL's help. See issue for additional context.
I'm not very familiar with dlme-transform, so if these files should live in a different repo (i.e. keeping them in the current directory will interfere with existing workflows), let me know. Transifex is completely agnostic to file path. Thanks!
No. I am currently working ondocumentation for our Transifex workflows across repos in [this google doc](https://docs.google.com/document/d/1Zu574lJNM55Diu_F0-aN6bIZ--aOKFw7Bqj0VPiYCNA/edit). I can add a wiki page if that's useful?

Add English source YML for Transifex workflow

---

traject_configs/harvard_ihp_config.rb

Add has type value to Harvard IHP
n/a

Add has type to Harvard

---

lib/macros/harvard.rb
traject_configs/harvard_ihp_config.rb

Fixes #466  for harvard. The example in the ticket now produces:
```
{"cho_title":{"none":["Hādhā Thabat al-Shihāb Aḥmad al-ʻAṭṭār : manuscript, 1900"]},"cho_alternative":{"none":["هذا ثبت الشهاب احمد العطار : مخطوطة، 1900"]},"cho_contributor":{"none":["ʻAṭṭār, Aḥmad Fahmī ibn Salīm (copyist.)","عطار، احمد بن عبيد الله، , 1725 or 1726-1803 or 1804"]},"cho_creator":{"en":["ʻAṭṭār, Aḥmad ibn ʻUbayd Allāh , 1725 or 1726-1803 or 1804"]},"cho_date":{"en":["1900"]},"cho_date_range_norm":[1900],"cho_date_range_hijri":[1317,1318],"cho_description":{"en":["Copy completed on 2 Dhū al-Ḥijjah 1317 [April 2, 1900] in the hand of Aḥmad Fahmī ibn Salīm ibn Yāsīn ibn Ḥāmid ibn al-Shihāb Aḥmad al-ʻAṭṭār, most probably in Damascus.","Bound with: Kitāb al-Fawāʼid al-jalīlah fī musalsalāt Ibn ʻAqīlah / …
```

Do not include empty agg_preview

---

lib/translation_maps/norm_languages_to_ar.yaml

The parenthesis are misplaced in the Arabic language values, I suspect because they looked the same but were different characters.
I loaded this in the local webapp (docker). The English looks fine but there is no Arabic site in the local version so I can't tell if this will resolve the problem.
n/a

Fix parenthesis in Arabic language values

---

lib/translation_maps/turkish-types.yaml

One value in the Turkish type translation map was incorrectly mapped
Transformed and viewed locally
n/a

Revise turkish type translation map

---

lib/translation_maps/norm_languages_to_ar.yaml

Parenthesis were on the wrong side
Can't test Arabic language changes locally
n/a

fix parenthesis in arabic translation map

---

lib/macros/csic.rb
spec/lib/traject/macros/csic_spec.rb
traject_configs/csic_config.rb

Extracts the expected 856u field that includes the appropriate URL desired for agg_is_shown_at. There can be several 856 blocks, with several values for 856u, this filters out anything that does not include the simurg url.
Unit test, manual verification by @jacobthill 
N/A

Add a CSIC macro to extract the proper is_shown_at from the simurg URL

---

spec/lib/traject/macros/csic_spec.rb

To make it easier to see how to extend this test code in the future and use RSpec machinery.
Unit test.
None.

Pull macro test code that does not need to vary into test setup

---

traject_configs/qnl_config.rb

The same value was mapped to cho_spatial and cho_coverage. The data partner felt cho_spatial was a better fit.
Not tested.
n/a

Remove cho_coverage

---

traject_configs/auc_university_on_square_coll7_config.rb

The extracted cho_has_type values were not found in the translation map so nothing was getting passed through to the IR. This removes the `downcase` so that the extracted values are found and mapped.
Transformed and viewed locally.
n/a

Fix sub types

---

Dockerfile

Because the base image is now based on Alpine 3.12 which requires this change. See https://stackoverflow.com/questions/62169568/docker-alpine-linux-python-missing
n/a
n/a

Specify python 3

---

traject_configs/harvard_scw_config.rb

The dates displayed were redundant and the rights statement applied to the physical object not the digital images. There is no statement for the digital images.
tested locally
n/a

revise harvard scw

---

Dockerfile

Fixes missing awscli command after python3 upgrade.
manually in dev

user pip3 to install python dependencies

---

Dockerfile

The pip3 installation of awscli makes the six installation unnecessary. 
Manually in AWS Dev

Do not install six dependency

---

Dockerfile

Fixes missing aws cli, without specifying `python3-dependencies` the cli is removed as unused.
Manually on ECS
N/A

Specify python3-dependencies

---

Dockerfile

This reverts the image to utilize python2 until we can solve python3 based dependency issues.
Manually tested

Pin docker base image to alpine 3.11

---

traject_configs/harvard_scw_config.rb

There were too many alternate titles displayed in the main title field.
locally
n/a

Remove alternate tiles from main title field

---

config/metadata_mapping.json
lib/macros/dlme.rb
lib/translation_maps/has_type.yaml
traject_configs/loc_abdul_hamid_ii_books_config.rb
traject_configs/loc_abdul_hamid_ii_photos_config.rb
traject_configs/loc_el_taher_config.rb
traject_configs/loc_greek_and_armenian_patriarchates_config.rb
traject_configs/loc_persian_config.rb
traject_configs/loc_st_catherines_monastery_config.rb

These collections are new to DLME. Mapping started a few months back but wasn't finished. Maps six collections, adds new language detection macros to assign language values to metadata fields (these will be broken out of dlme.rb in the future), updates metadata settings (one country intentionally left blank) and translation map.
Locally tested as much as possible in the docker app. Also used mapping analysis scripts.
n/a

Map LOC collections

---

traject_configs/loc_abdul_hamid_ii_books_config.rb
traject_configs/loc_abdul_hamid_ii_photos_config.rb
traject_configs/loc_greek_and_armenian_patriarchates_config.rb
traject_configs/loc_persian_config.rb
traject_configs/loc_st_catherines_monastery_config.rb

iiif manifest urls weren't displaying for some collections because urls were http instead of https, language values weren't present in one collection, description field missing in one collection.
Tested language and description field with local scripts. No way to test iiif since the local docker app displays iiif manifests with http urls.
n/a

Revise LoC mapping

---

config/metadata_mapping.json
traject_configs/loc_abdul_hamid_ii_books_config.rb

Some records weren't loading because of the missing country value, one collection didn't have the iiif manifest for the agg_is_shown_at field.
not tested
n/a

Revise LoC

---

traject_configs/loc_el_taher_config.rb

Fix a few errors in LOC el-Taher collection
- remove trailing backslash in title field
- one photograph had a cho_edm_type value of 'Text' instead of 'Image'.
Local transform viewed in the dev site.
loc_el_taher_config.rb, no documentation update necessary

fix edm_type

---

lib/macros/lausanne.rb
spec/lib/traject/macros/laussane_spec.rb

A suggestion to fix the complexity violation of the lausanne macros.

Simplify the lausanne macros to limit complexity

---

lib/macros/dlme.rb
spec/lib/traject/macros/dlme_spec.rb
traject_configs/aub_aco_config.rb
traject_configs/aub_common_config.rb
traject_configs/auc_qurna_coll24_config.rb
traject_configs/cambridge_config.rb
traject_configs/manchester_genizah_config.rb
traject_configs/manchester_hebraica_config.rb
traject_configs/manchester_nashriyah_config.rb
traject_configs/manchester_papyri_config.rb
traject_configs/vatican_config.rb

cho_title is a required field, but several datasets have records without titles. The default macro in traject needed to be updated to work with our hashing. A new strategy of passing truncated descriptions in the case that no titles are found in the record has been recently adopted.
Local transformations and analysis scripts
n/a

Revise/add macros and tests for missing titles, fixes #613

---

lib/macros/cambridge.rb

address rubocop complaints on #628

macros/cambridge.rb: refactor cambridge_dimensions to reduce inline complexity and code duplication

---

lib/macros/string_helper.rb

Removes custom logic that is mirrored in activesupport

Simple update to the proposed macros to use standard activesupport methods

---

lib/contracts/cho.rb

cho_edm_type and cho_has_type need to be required fields, either they are extracted from the metadata or manually assigned.
these fields were already required according to the https://github.com/sul-dlss/dlme/blob/master/docs/application_profile.md

Make cho_edm_type and cho_has_type required fields

---

README.md

They no longer work and microbadger is shutting down

Remove microbadger tags

---

lib/translation_maps/norm_has_type_to_ar.yaml
traject_configs/auc_oai_historical_videos_config.rb

The cho_has_type field was changed to a required field some time back and this mapping was not updated at that time.
n/a

update AUC mapping

---

lib/translation_maps/getty_aat_material_ar_from_en.yaml
lib/translation_maps/temporal_ar_from_en.yaml

Needed to align values from English translation maps with keys in Arabic
local analysis scripts
n/a

add getty material values

---

lib/translation_maps/edm_type_from_has_type.yaml
lib/translation_maps/spatial_ar_from_en.yaml
spec/lib/translation_maps/validate_contributor_translation_maps_spec.rb

* use it to test a couple sets of mappings, including one skipped for now due to known lack of translations
* add a missing translation caught by the tests
closes #722 
closes #723
closes #724 
closes #725 
closes #726 
closes #727 
closes #728 
closes #729
see also #738
see also #740
see also #741 
see also #742
see also #743 
see also #744
unit tests
translation config

add a shared_example for validating translation maps

---

lib/macros/normalize_type.rb
spec/lib/traject/macros/harvard_ihp_spec.rb
spec/lib/traject/macros/harvard_scw_spec.rb
spec/lib/traject/macros/laussane_spec.rb
spec/lib/traject/macros/manchester_spec.rb
spec/lib/traject/macros/normalize_type_spec.rb

closes #701
also, some opportunistic touchups in the second commit (discovered the unused `let` vars while looking for testing patterns i could copy).
unit tests
n/a

 Remove generic cho_has_type value when specific value present

---

traject_configs/aims_config.rb
traject_configs/antiquities_coalition_config.rb
traject_configs/aub_poha_config.rb

A new test to catch missing language keys was written. This PR adds keys to fields that are missing them so that PR can be merged.
n/a

add missing langauge keys

---

traject_configs/qnl_config.rb

Fixes #759 
QNL is the only collection where we were inserting bad data into the `agg_preview` hash conditionally if a iiif manifest is not available. By inserting non-urls into `agg_preview.wr_id` blacklight broke attempting to render bad URLs, this resolves that.
Ran in dev, manual analysis, and existing integration tests.

Do not insert bad data when a iiif manifest is not available for QNL

---

README.md
spec/spec_helper.rb

makes it easier to see what's breaking the build in CI, where stdout and stderr output can easily overrun CircleCI's limit for in-browser output display.
extracted from #761, since that's taking a little while to figure out, and this is generally useful.
* ran unit tests locally
* confirmed that `STDOUT` and `STDERR` are both squelched by default, and that logger output is always shown
* confirmed that `NO_SQUELCH_STDERR` flag works
* confirmed that `NO_SQUELCH_STDOUT` flag works
* CI
`spec_helper.rb`, `README.md`

silence stdout and stderr during tests

---

traject_configs/lausanne_ias_config.rb

Some Lausanne records were missing titles
n/a

Fix Lausanne missing title errors

---

traject_configs/aub_poha_config.rb

at least one AUB record did not have a thumbnail and was failing type validation
n/a

don't return null when no preview

---

config/honeybadger.yml

By default, honeybadger outputs an initialization message that gets inserted into our output. This causes a bug with parsing JSON later in the ingestion process. By setting the honeybadger log level to warn (per: https://github.com/honeybadger-io/honeybadger-ruby/issues/296) that message no longer appears in our output.

Remove Honeybadger initialization warning from output

---

lib/macros/each_record.rb
spec/lib/traject/macros/each_record_spec.rb

- The HTML warning is very noisy and not needed since we can't change the raw data and there is no way we introduced the HTML during mapping.
- Local rspec
n/a

remove html warning, fixes #785

---

README.md
invoke.sh

This is a small PR to allow for optionally setting the data_dir via the environment. This will enable airflow to trigger the DLME transform task in ECS without the command line parameter. 
Manually
README

Add option to set DATA_DIR in environment for transform run

---

.circleci/config.yml
README.md

As the current work flow currently only utilizes dlme-transform in the development environment and dlme-transform is run as an ECS task and not a service, the image is pulled when the task is invoked. This makes the development deployment steps unnecessary and complicates stage and prod where this is rarely used.

Simplify deployment instructions

---

Gemfile

Note is no longer needed;  version specification is enough.

Gemfile: remove note about simplecov version needs

---

.circleci/config.yml

Switch to non-deprecated circleci images

---

.circleci/config.yml

basing it on https://github.com/sul-dlss/dlme/pull/1382 -- the "build" circleci "build" failed "building" the docker-image with the new `cimg/base`

use docker image to publish that will work

---

README.md

Replace `be` aliases with full `bundle exec` for clarity

Update README to remove aliased references

---

.circleci/config.yml

Use ruby 3.0 image to build and publish the image

---

README.md
invoke.sh

This refactors the existing docker invoke so that the fetch data step does not download the entire data set as a github zip file, but instead fetches only the required data from S3.

Refactor docker invoke to fetch data from S3 instead of github

---

invoke.sh

the new path is `metadata` to match output during comparison.

Update invoke.sh to use updated s3 path

---

.dockerignore
.gitignore

This will help avoid accidentally building test data into the image locally which causes issues when the metadata extraction steps.

Add dlme-metadata-main and main.zip to ignore files

---

traject_configs/walters_config.rb

Walters urls had redirect errors (http://art.thewalters.org/detail/84358 -> https://art.thewalters.orgdetail/84358). This guards against that but also should still work if they update their data.
n/a

guard against walters redirect error

---

config/metadata_mapping.json

The configuration for `auc/iiif/university-on-the-square` is currently duplicated. This removes the second instance.

Remove duplicate collection configuration

---

traject_configs/aub_aco_config_csv.rb
traject_configs/aub_aladab_config_csv.rb
traject_configs/aub_poha_config_csv.rb
traject_configs/aub_postcards_config_csv.rb
traject_configs/aub_posters_config_csv.rb
traject_configs/aub_travelbooks_config_csv.rb

This is a follow up to the earlier AUB macro. The `dlme_source_file` is used during reporting, where it was surfaced that this field is missing.

Add missing macro to AUB

---

traject_configs/bodleian_hebrew.rb

Bodleian hebrew currently fails transform due to this missing macro.

Include csv macro in bodleian hebrew

---

traject_configs/princeton.rb

The current order splits the text of the thumbnail data too early causing it not to parse properly. We need to do `parse_csv` first in most cases to convert some strings to arrays.

Change order of macros on Princeton thumbnail extraction

---

traject_configs/aims.rb

To include missing dlme_source_file field

Add dlme_source_file to aims config

---

.rubocop.yml
Gemfile
Gemfile.lock
lib/dlme_debug_writer.rb
lib/dlme_json_resource_writer.rb
lib/macros/cambridge.rb
lib/macros/date_parsing.rb
lib/macros/each_record.rb
lib/macros/qnl.rb
spec/lib/traject/macros/cambridge_spec.rb
spec/lib/traject/macros/each_record_spec.rb
spec/lib/traject/macros/iiif_spec.rb
spec/lib/traject/macros/string_helper_spec.rb

This is just a rubocop update. This unpins the rubocop gem(s) and enable new cops, then corrects any linting issues raised by the new cops.

Enable new cops and remove old cops that throw errors

---

lib/macros/csv.rb

Fixes #939 
Since often the array from the CSV becomes nested, we need to compact the array.

Avoid outputting nil when parsing csv array values

---

lib/macros/csv.rb
spec/lib/traject/macros/csv_spec.rb
traject_configs/qnl.rb

Added a `parse_yaml` function to handle some edge case titles from QNL which contain single-quotes enclosing some text a comma which in turn throws a CSV parser error.
I think we can parse all the lists as YAML, without needing to strip square brackets, and extraneous white space. But @aaron-collier thought it might be safer to add a new function for use exclusively with QNL titles, and then use it more broadly if it proves to work ok.
Added a new test for the edge case.

Handle Python list in CSV edge cases

---

lib/macros/dlme.rb

`at_index` currently introduces a bug where if there is no value at `acc[index]` the accumulator is replaces with an array of a single nil element (i.e. `[nil]`) this is causing a breaking error in traject.
Manual transform of QNL (20k records)

Only update the accumulator if there is a value at the provided index

---

lib/translation_maps/edm_type_from_has_type.yaml

The duplicate key was causing issues in transifex

remove duplicate key

---

Dockerfile
invoke.sh

Removes dependency on S3 and fetches/writes data to mounts established in the DockerOperator.
Connected to: https://github.com/sul-dlss/dlme-airflow/pull/350

Update invocation to so it runs as a DockerOperator in airflow on prem.

---

config/metadata_mapping.json
traject_configs/qnl.rb

Switch QNL to JSON parsing
This switches QNL transform parsing from CSV to JSON in order to address character encoding issues discovered in the CSV.

Switch QNL to JSON parsing

---

invoke.sh

This takes a data path as `sakip_sabanci_museum/abidin_dino` and ensures the output file is `output-sakip-sabanci-museum-abidin-dino.ndjson`

This ensures the full translation of data path to filename

---

traject_configs/palestine_posters_project_archive.rb

There was an error in the resource urls caused by passing a full url in the id field; this fixes that issue.
n/a

fix error in pppa id url

---

traject_configs/shahre_farang.rb

Id field still had full url for a few records
local transform and load in review
n/a

fix id field

---

traject_configs/ucla_iiif_v3.rb

The id value in the iiif_v3 was a full url which prevents the records from resolving.
n/a

fix id in iiif_v3 collections

---

lib/contracts/cho.rb
traject_configs/bnf.rb
traject_configs/cambridge_genizah.rb
traject_configs/cambridge_hebrew.rb
traject_configs/cambridge_islamic.rb
traject_configs/loc.rb
traject_configs/sakip_sabanci_museum.rb

We have a number of records that fail to resolve because the record id is a url. These records resolved in the past but stopped working some time ago.
n/a

add DRY validation for url in id field

---

.gitignore
Gemfile
Gemfile.lock
lib/macros/csic.rb
lib/macros/csv.rb
spec/spec_helper.rb

Replaces byebug with the now standard debug, where `byebug` was used as a breakpoint before, `debugger` is now used.

Switch from byebug to debug

---

Gemfile
Gemfile.lock

Pin ffi to avoid platform mismatch.

Pin ffi to a supported version

---

Gemfile
Gemfile.lock

This dependency is moving out of stdlib in Ruby 3.4 so it must be managed by bundler.
CI

Add csv dependency to bundler

---

README.md
invoke.sh

Otherwise all of STDOUT goes into the airflow logs.

Quiet logging to avoid issues in airflow

---

config/metadata_mapping.json
config/settings.yml
lib/contracts/cho.rb
lib/macros/date_parsing.rb
lib/macros/field_extraction.rb
lib/macros/normalize_type.rb
lib/macros/prepend.rb
lib/macros/transformation.rb
lib/translation_maps/has_type_from_collection.yaml
lib/translation_maps/lang_from_downcased.yaml
lib/translation_maps/lang_from_errors.yaml
spec/lib/contracts/cho_spec.rb
spec/lib/traject/macros/field_extraction_spec.rb
spec/lib/traject/macros/transformation_spec.rb
traject_configs/auc.rb

AUC was still using csv data and needed to switch to json. The json records contain nil values which causes, `strip`, `gsub`, `prepend`, etc. to fail. This adds new versions of those macros that guard against that. We are also seeing some errors with the values that get into `cho_edm_type` and `cho_has_type` so this treats those values as a controlled vocabulary and raises an error when a value not in the list is found. I'm planning a follow up PR to add nil-safe versions of all of the rest of the macros in https://github.com/traject/traject/blob/main/lib/traject/macros/transformation.rb. But this will require moving some things around and updating all of the configs that use them. Also planning another PR to remove all of the xml and csv macros that we no longer need.
Local transform, …

Move AUC to json, add validation, adjust macros

---

lib/macros/transformation.rb

Ensure that `nil` values are removed from the accumulator to avoid raising errors unexpectedly when `dlme_strip` is used

Ensure no nils are used when subbing

---

traject_configs/penn_museum.rb

The file path in Airflow seems to have changed. I used to select the select the collection name with `to_field 'agg_data_provider_collection', path_to_file, split('/'), at_index(2)` and now I need `to_field 'agg_data_provider_collection', path_to_file, split('/'), at_index(4)`. This seems to work but other collections may need to be updated.
n/a

change file path index for collection id

---

traject_configs/princeton.rb

File path issues causing transform to fail. Princeton file path in traject looks like `/princeton/shahnameh/data.json` but penn looks like `/penn_museum//babylonian/data.json`. I need to open a ticket to investigate why some paths have extra slashes.
n/a

fix princeton file path

---

lib/macros/path_to_file.rb
traject_configs/auc.rb
traject_configs/penn_museum.rb

For some reason, some values returned from `path_to_file` have `//` which causes issues when we use `path_to_file` to build the collection name.
n/a

clean up some issues with path_to_file

---

traject_configs/aub.rb
traject_configs/auc.rb
traject_configs/auc_serials.rb
traject_configs/bnf.rb
traject_configs/bodleian.rb
traject_configs/brooklyn.rb
traject_configs/cambridge_genizah.rb
traject_configs/cambridge_hebrew.rb
traject_configs/cambridge_islamic.rb
traject_configs/gottingen.rb
traject_configs/koch.rb
traject_configs/lebanese_american_university.rb
traject_configs/leiden.rb
traject_configs/loc.rb
traject_configs/newcastle.rb
traject_configs/openiti.rb
traject_configs/penn_museum.rb
traject_configs/princeton.rb
traject_configs/sakip_sabanci_museum.rb
traject_configs/ucla_armenian.rb
traject_configs/ucla_iiif.rb
traject_configs/ucla_no_preview.rb
traject_configs/walters.rb

When using the path name to lookup the collection provider, always use the index -2 as the path array is:
[......, 'provider_collection', 'data.json']
Therefore the -2 index (second from last item) is always the key for the collection lookup.

Always get last path before filename for collection lookup

---

traject_configs/auc_serials.rb

There was a weird mapping bug. https://dlmenetwork.org/library/catalog?f%5Bagg_provider_en%5D%5B%5D=American+University+in+Cairo maybe because of `transform(&:to_s)` but this field isn't needed and doesn't make any sense in the context so removing for now with a note to self.

comment out size field

---

lib/contracts/edm_web_resource.rb
spec/lib/contracts/cho_spec.rb

To prevent loading records with invalid urls in fields expecting urls.

add url validation

---

Gemfile
Gemfile.lock

Let traject deal with it on behalf of httpclient. It's not a direct dependency so let's not manage it.
CI

Remove explicit dependency on mutex_m

---

Gemfile
Gemfile.lock

I don't think we need to pin this dependency tightly here.

Unpin ActiveSupport to allow upgrades
