- Dockerfile
- Gemfile
- Gemfile.lock
- README.md
- invoke.sh
> Create Dockerfile that runs traject.

- Dockerfile
- README.md
- invoke.sh
> Adds optional fetching of configs and data from github.

- Dockerfile
- README.md
- invoke.sh
> Adds optional upload to S3.

- README.md
- invoke.sh
> Volumes must provide a full local path

- README.md
I was seeing errors when running the bnf_cealex_config that I don't see with the mods
> Use an example that we know works

- README.md
- invoke.sh
> Allow pulling new configs, without pulling metadata

- lib/transformer.rb
- spec/lib/transformer_spec.rb
> Adds command_line.filename to index settings.

- Dockerfile
- README.md
- invoke.sh
- lib/cli.rb
- lib/record_counter.rb
- lib/record_counter_config.rb
- lib/transformer.rb
- spec/lib/cli_spec.rb
- spec/lib/transformer_spec.rb
- spec/spec_helper.rb
> Adds optional SNS notification containing results summary.

- lib/cli.rb
- spec/lib/cli_spec.rb
> Adds data path and duration to notification message.

- lib/cli.rb
- lib/dlme_debug_writer.rb
- lib/dlme_json_resource_writer.rb
- lib/line_writer_fix_mixin.rb
- lib/transformer.rb
- spec/lib/cli_spec.rb
- spec/lib/transformer_spec.rb
> Adds patched debug writer. Adds debug writer as commandline option.

- metadata_mapping.json
> Added metadata mappings for existing collections.

- Gemfile
- Gemfile.lock
- lib/dlme_utils.rb
- lib/macros/met_csv.rb
Fixes  sul-dlss/dlme-traject#10
> Fix MetThumbnailFetcher

- .rubocop.yml
- lib/macros/bnf.rb
- lib/macros/dlme.rb
> Add macro for namespaces from Bibliothèque nationale de France

- README.md
- lib/dlme_json_schema.rb
> Adds validation for unmapped languages to cho_language and cho_edm_type.

- lib/dlme_utils.rb
- lib/met_thumbnail_fetcher.rb
- spec/lib/met_thumbnail_fetcher_spec.rb
> Update the thumbnail fetcher to use the new API

- README.md
- lib/translation_maps/not_found.rb
- spec/lib/translation_maps/not_found_spec.rb
> Provide unmapped language value in addition to NOT_FOUND.

- spec/lib/translation_maps/not_found_spec.rb
> Adds additional test for NOT FOUND.

- lib/macros/bnf.rb
- lib/macros/srw.rb
> Provide an extract_srw macro

- .gitignore
- lib/macros/bnf.rb
- lib/macros/csv.rb
- lib/macros/dlme.rb
- lib/macros/dlme_marc.rb
- lib/macros/fgdc.rb
- lib/macros/iiif.rb
- lib/macros/met_csv.rb
- lib/macros/mods.rb
- lib/macros/numismatic_csv.rb
- lib/macros/stanford.rb
- lib/macros/tei.rb
- spec/lib/traject/macros/met_csv_spec.rb
> Add API documentation

- .circleci/config.yml
> Adds building and pushing docker container to circleci.

- lib/macros/oai.rb
> Add a macro for getting the oai identifier

- lib/translation_maps/auc-languages-errors.yaml
- lib/translation_maps/languages.yaml
- lib/translation_maps/turkish-languages.yaml
@anarchivist I accidentally deleted a file and it was easier to abandon that pull request and start a new branch. I think this takes care of it.
> break up language maps

- .circleci/config.yml
refs https://github.com/sul-dlss/dlme/issues/499
> Update circleci config to build latest and tagged images.

- Dockerfile
- invoke.sh
> Switched to uuidgen.

- lib/macros/content_dm.rb
(ref sul-dlss/dlme-traject#59)
> Add macro for thumbnails from CONTENTdm

- lib/macros/content_dm.rb
> Refactor CONTENTdm macros to get procs (fixes #141)

- lib/dlme_utils.rb
- lib/macros/iiif.rb
Instead put just doing a `puts` on the error, use the logger.
> Use the logger instead of puts

- README.md
and update alt text and tooltips for image and commit badges
Fixes #199
> README: add circleCI badge 

- .circleci/config.yml
- .gitignore
- Gemfile
- Gemfile.lock
- README.md
- spec/spec_helper.rb
> add code coverage (no need for parallel rspec builds)

- Gemfile
- Gemfile.lock
To allow for dependency upgrades.
n/a
> Relax TrajectPlus pinning now that bug sul-dlss/traject_plus#33 is fixed

- Dockerfile
> Use bundler version from Gemfile.lock in containerland

- lib/macros/dlme.rb
part of sul-dlss/dlme-traject#111
code documentation is inline
> new macro functions to fetch values from metadata_mappings.json

- lib/dlme_json_schema.rb
part of sul-dlss/dlme-traject#111
n/a
> [HOLD UNTIL MONDAY SEP 30] validate existence of new fields coming from macro

- lib/translation_maps/norm_types_to_ar.yaml
Add Arabic values for cho_edm_type
NA
> add Arabic translation map for cho_edm_type, closes #171

- Gemfile
- Gemfile.lock
Adds the hijri gem as part of #189 
N/A
> Add the hijri gem

- lib/macros/fgdc.rb
- lib/macros/mods.rb
- removes old collection level normalization code in favor of the recent updates
- updated configs in https://github.com/sul-dlss/dlme-traject/pull/140
NA
> remove old normalization code, closes #144

- lib/contracts/cho.rb
- spec/lib/contracts/cho_spec.rb
And spruce up validation logic.
To allow sul-dlss/dlme-traject#139 to be merged.
N/a.
> Validate language-specific fields as hashes

- lib/macros/normalize_language.rb
I was having trouble understanding how the code worked together. I believe this makes it easier to read.
n/a
> Refactor NormalizeLanguage for readability

- traject_configs/marc_config.rb
Reverts sul-dlss/dlme-transform#273
Went early
> Revert "penn/marc gets cho_date_range_norm"

- lib/macros/date_parsing.rb
- spec/lib/traject/macros/date_parsing_spec.rb
- traject_configs/numismatic_csv_config.rb
- Adds macro to parse American Numismatic Society dates
- Calls macro in numismatic_config.rb
- Adds tests for macro
n/a
> American numismatic date parsing

- .rubocop.yml
- lib/macros/date_parsing.rb
- spec/lib/traject/macros/date_parsing_spec.rb
- traject_configs/met_config.rb
- traject_configs/michigan_config.rb
- traject_configs/numismatic_csv_config.rb
- Adds macro to parse Met dates
- Calls macro in met_config.rb
- Adds tests for macro
n/a
> Parse Met dates

- lib/translation_maps/norm_has_type_to_ar.yaml
To update the cho_has_type translations based on feedback from QNL
n/a
> update cho_has_type translations

- config/metadata_mapping.json
- lib/macros/date_parsing.rb
- spec/lib/traject/macros/date_parsing_spec.rb
- traject_configs/sakip_mult_dates_config.rb
- traject_configs/sakip_sabanci_common_config.rb
- traject_configs/sakip_single_date_config.rb
closes #188, #258
Sakip collections get date range fields populated
n/a
> Sakip collections get date ranges

- spec/lib/traject/macros/date_parsing_spec.rb
I missed this in the prior PR that closed #321. This PR has a few different components, a couple of which were opportunistic and not necessarily required:
1. Test that the `parse_range` macro does not return `nil`s in its array. This condition causes the `hijri_range` macro to raise `NoMethodError`.
2. Tweak a couple test descriptions to read as more idiomatic English.
3. Prefer using a lambda over TrajectPlus `accumulate` macro when doing test setup, since the latter has a notable side effect of removing `nil` values, which can hide errors that we will not find until later (as our configs do not use `accumulate`).
no
> Add a test for date range normalization

- lib/macros/aims.rb
- traject_configs/aims_config.rb
Needed to revise AIMS mapping to reflect changes to the IR and add language keys.
n/a
> Revise AIMS transform to add language values, fixes #348

- traject_configs/auc_common_config.rb
- Revise AUC mapping
Opened a ticket to apply language fields later. This is a particularly challenging data set and I need to figure out how to approach it when I have more time. https://github.com/sul-dlss/dlme-transform/issues/367
n/a
> Revise AUC mapping

- traject_configs/cambridge_config.rb
- Revise Cambridge mapping
n/a
> Revise Cambridge mapping, fixes #342

- traject_configs/met_config.rb
- Revise Met mapping
- Removes mismapped field
- Adds cho_has_type 
n/a
> Revise Met mapping, fixes #350

- config/metadata_mapping.json
- traject_configs/numismatic_csv_config.rb
- Revise ANS mapping
- Update metadata-mappings
n/a
> Revise ANS mapping, fixes #347

- traject_configs/pppa_config.rb
- revise pppa mapping
- adds fields for cho_has_type
n/a
> Revise Palestine Posters config, fixes #352

- lib/macros/each_record.rb
- spec/lib/traject/macros/each_record_spec.rb
- traject_configs/aims_config.rb
- traject_configs/aub_aladab_config.rb
- traject_configs/aub_postcards_config.rb
- traject_configs/auc_common_config.rb
- traject_configs/bnf_ideo_config.rb
- traject_configs/bnf_ifao_config.rb
- traject_configs/bodleian_config.rb
- traject_configs/cambridge_config.rb
- traject_configs/cluster_config.rb
- traject_configs/fgdc_config.rb
- traject_configs/harvard_ihp_config.rb
- traject_configs/met_config.rb
- traject_configs/michigan_config.rb
- traject_configs/numismatic_csv_config.rb
- traject_configs/openn_common_config.rb
- traject_configs/penn_museum_config.rb
- traject_configs/pppa_config.rb
- traject_configs/princeton_movie_config.rb
- traject_configs/princeton_mss_config.rb
- traject_configs/qnl_config.rb
- traject_configs/sakip_sabanci_common_config.rb
- traject_configs/stanford_mods_config.rb
Closes #383 - Access team needs field to support hierarchical facet display 
I confirmed values with Jessie and Aaron.  This may not be perfect, but it is hopefully enough for Access to be unblocked on this.
After this is merged, we should push a new docker image and redeploy to ... dev?
n/a -- I can't think of a place appropriate to document this.
>  add_cho_type_facet  - new each_record macro for hierarchical facet field

- README.md
This repo had no documentation for how to deploy changes to AWS;  these changes to the README fill in that gap.
yes, README
> README: add deployment information

- README.md
I noticed a couple typos and some missing information when I was working on deploying dependency updates this morning.
yes, README.
> README tweaks for deployment instructions

- config/settings.yml
- spec/lib/contracts/cho_spec.rb
> Allow Turkish language without script designation

- traject_configs/sakip_sabanci_common_config.rb
- revise Sakip Sabanci mapping
n/a
> Revise Sakip Sabanci mapping, fixes #356

- lib/macros/penn.rb
- traject_configs/penn_museum_config.rb
> Remap Penn museum

- traject_configs/bodleian_config.rb
- revise Bodleian mapping 
- n/a
> Revise Bodleian mapping, fixes #343

- lib/translation_maps/norm_languages_to_ar.yaml
- traject_configs/fgdc_config.rb
- traject_configs/harvard_ihp_config.rb
- Revise Harvard mapping
- Add new language values in Arabic
- Open ticket to re-harvest the maps collection https://github.com/sul-dlss/dlme-transform/issues/410
- n/a
> Revise Harvard mapping

- lib/translation_maps/languages.yaml
- lib/translation_maps/norm_languages_to_ar.yaml
- traject_configs/bodleian_config.rb
- Fix some mapping errors in the Bodleian language fields
- n/a
> Fix Bodleian language mapping errors

- lib/contracts/cho.rb
- spec/lib/contracts/cho_spec.rb
> Update contract rule to raise error on NOT FOUND

- lib/macros/penn.rb
- traject_configs/penn_museum_config.rb
- revise the Penn museum type mappings
- n/a
> Revise Penn type mapping

- lib/macros/dlme.rb
- traject_configs/bodleian_config.rb
Adds a formated iiif manifest for bodleian collections.
> Format iiif manifest based on bodleian homepage value

- traject_configs/bodleian_config.rb
- add iiif manifest directly
- remap cho_has_type Arabic
- n/a
> Revise Bodleian transform

- config/metadata_mapping.json
- lib/macros/date_parsing.rb
- traject_configs/stanford_mods_config.rb
Revision of #436 
- Revise Stanford mapping
- n/a
> Update Stanford transform configuration

- lib/translation_maps/norm_has_type_to_ar.yaml
- lib/translation_maps/turkish_has_type_to_en.yaml
- Add English translations of missing Turkish types to map in sub types
- Add Arabic translations of the above
-n/a
> Update Turkish types and Arabic translations

- traject_configs/cluster_config.rb
> Add CLUSTER mapping

- config/metadata_mapping.json
- traject_configs/shahre_farang_arabic_config.rb
- traject_configs/shahre_farang_english_config.rb
- traject_configs/shahre_farang_persian_config.rb
- Add new configs to map three collections from Shahre Farang
n/a
> Add Shahre Farang mapping

- config/metadata_mapping.json
- lib/macros/date_parsing.rb
- lib/translation_maps/norm_languages_to_ar.yaml
- spec/lib/traject/macros/date_parsing_spec.rb
- traject_configs/harvard_scw_config.rb
Map the Harvard Stuart Cary Welch collection
- Add macro to parse dates from dateCreated field only
- Add Arabic translation 'no language content'
n/a
> Harvard scw

- lib/macros/cambridge.rb
- traject_configs/cambridge_config.rb
Fixes #440 
@jacobthill please transform and verify.
> Add appropriate regex for cambridge id

- traject_configs/cambridge_config.rb
> Problem with setting default for missing title

- config/metadata_mapping.json
- lib/translation_maps/language-errors.yaml
- lib/translation_maps/languages.yaml
- lib/translation_maps/norm_languages_to_ar.yaml
- traject_configs/loc_abdul_hamid_ii_books_config.rb
- traject_configs/loc_abdul_hamid_ii_photos_config.rb
- traject_configs/loc_el_taher_config.rb
- traject_configs/loc_greek_and_armenian_patriarchates_config.rb
- traject_configs/loc_persian_config.rb
- traject_configs/loc_st_catherines_monastery_config.rb
- Add mappings for six new LOC collections
- Add new languages to `languages.yaml`
- Add Arabic equivalents to `norm_languages_to_ar.yaml`
n/a
> Add LOC mappings

- traject_configs/shahre_farang_arabic_config.rb
- traject_configs/shahre_farang_persian_config.rb
- Update language values for Shahre Farang records
- n/a
> Fix language values

- config/metadata_mapping.json
- traject_configs/antiquities_coalition_config.rb
Add Antiquities Coalition mapping
n/a
> Add Antiquities Coalition mapping

- traject_configs/loc_abdul_hamid_ii_books_config.rb
- traject_configs/loc_abdul_hamid_ii_photos_config.rb
- traject_configs/loc_el_taher_config.rb
- traject_configs/loc_greek_and_armenian_patriarchates_config.rb
- traject_configs/loc_st_catherines_monastery_config.rb
Revise loc mappings, fix iiif errors
n/a
> Revise loc mappings

- config/metadata_mapping.json
- traject_configs/auc_university_on_square_coll7_config.rb
> Map AUC University on the Square collection

- traject_configs/harvard_ihp_config.rb
- traject_configs/harvard_scw_config.rb
Get thumbs for SCW collection
n/a
> Fix SCW thumbs

- traject_configs/csic_config.rb
> Revise CSIC mapping

- traject_configs/loc_abdul_hamid_ii_photos_config.rb
> Fix thumbnail url error

- config/metadata_mapping.json
- traject_configs/csic_config.rb
- Construct thumbnail from id and url pattern
- Change provider name based on partner feedback
n/a
> Add thumbs and fix provider name

- config/settings.yml
- lib/contracts/cho.rb
- lib/macros/path_to_file.rb
- spec/lib/traject/macros/path_to_file.rb
- traject_configs/qnl_config.rb
This should help in chasing down problematic data sources.
- add a macro to return file path
- add a test for the macro
- add new field to map file path to
- configure validation for new field
Documentation: https://github.com/sul-dlss/dlme/pull/861
> Add file path to IR

- traject_configs/harvard_scw_config.rb
#517  Why was this change made?
- fix bad urls for agg_preview
- fix bad urls for agg_is_shown_at
- remove bad iiif manifests for both
n/a
> Fix broken agg_preview, agg_is_shown_at urls and bad iiif manifests

- config/metadata_mapping.json
- AIMS is in multiple countries; the other countries were added.
n/a
> Add countries to AIMS records

- lib/translation_maps/has_type.yaml
- lib/translation_maps/iso_639-3.yaml
- traject_configs/qnl_config.rb
- Fix errors in QNL mapping
- Remove language pluralization from translation maps
- Add translation map for sub types
- n/a
> Qnl mapping

- traject_configs/loc_greek_and_armenian_patriarchates_config.rb
- traject_configs/loc_persian_config.rb
- traject_configs/loc_st_catherines_monastery_config.rb
- remove iiif manifests that had no canvases
- n/a
> remove iiif manifests

- .circleci/config.yml
- Dockerfile
> Update to ruby 2.7.1 in circle and docker

- traject_configs/texas_tech_config.rb
The type field was not  displaying.
Loaded and visually inspected locally.
n/a
> Fix type values in Texas Tech data

- traject_configs/aub_aco_config.rb
- traject_configs/aub_travelbooks_config.rb
Fix AUB type 
Locally transformed and viewed
n/a
> fix AUB mapping

- traject_configs/cambridge_config.rb
Thumbnails were not displaying
n/a
> Fix cambridge thumbs

- Dockerfile
Make sure we install the proper six dependency.
Manual
> Ensure proper six installation

- config/metadata_mapping.json
- traject_configs/harvard_scw_config.rb
The attribution was not correct
locally
n/a
> Update attribution for Harvard SCW

- traject_configs/harvard_scw_config.rb
One metadata field was mislablelled and the iiif manifests were missing
Error in local app, didn't test
n/a
> Add iif manifest, etc.

- README.md
- invoke.sh
Closes https://github.com/sul-dlss/dlme/issues/1045
Local run
README
> Update docker invoke to allow for pushing to S3 from a local transform

- config/metadata_mapping.json
- lib/macros/aub.rb
- lib/macros/language_extraction.rb
- lib/translation_maps/types.yaml
- traject_configs/aub_poha_config.rb
To map new collections from AUB.
Local transform viewed in dev.
No documentation needed.
> Add config for new AUB collections

- config/metadata_mapping.json
- traject_configs/vatican_config.rb
Adding new dataset.
Local transform viewed in dev. 
n/a
> Initial Vatican mapping

- config/metadata_mapping.json
- lib/macros/language_extraction.rb
- lib/translation_maps/languages.yaml
- lib/translation_maps/norm_languages_to_ar.yaml
- spec/lib/traject/macros/language_extraction_spec.rb
- traject_configs/bodleian_arabic_config.rb
- traject_configs/bodleian_egypt_config.rb
- traject_configs/bodleian_hebrew_config.rb
- traject_configs/bodleian_persian_config.rb
- traject_configs/bodleian_turkish_config.rb
- New collections from Bodleian added
- Local transform and view in dev
n/a
> Map Bodleian records

- config/metadata_mapping.json
- lib/translation_maps/languages.yaml
- traject_configs/manchester_genizah_config.rb
- traject_configs/manchester_hebraica_config.rb
- traject_configs/manchester_nashriyah_config.rb
- traject_configs/manchester_papyri_config.rb
Added new Manchester collections.
Local transform and load in dev
n/a
> Map Manchester collections

- config/metadata_mapping.json
- lib/macros/date_parsing.rb
- lib/macros/lausanne.rb
- spec/lib/traject/macros/laussane_spec.rb
- traject_configs/lausanne_ias_config.rb
Adding a new collection 
Locally and viewed in dev
n/a
> Add Lausanne mapping

- .circleci/config.yml
- README.md
- docs/README.md
- invoke.sh
Updated references to the default branch as `main`
> Replace master reference with main

- config/metadata_mapping.json
- traject_configs/sakip_mult_dates_config.rb
- traject_configs/sakip_single_date_config.rb
- traject_configs/ssm_abidindino_xml_config.rb
- traject_configs/ssm_iiif_config.rb
-Reharvested Sakip Sabanci Museum records and needed to update mapping.
-Tested locally and loaded in dev.
-n/a
> Update Sakip Sabanci Museum mapping

- traject_configs/cambridge_genizah_config.rb
- traject_configs/cambridge_hebrew_config.rb
- traject_configs/cambridge_islamic_config.rb
- Add larger thumbs
- Clarify rights statements
- Local transform and load in dev
- Updated data partner profile in google drive
> update cambridge configs

- traject_configs/manchester_nashriyah_config.rb
Added missing rights statements
Local transform and load in dev
n/a
> Add rights statements

- lib/translation_maps/lausanne_types.yaml
- traject_configs/lausanne_ias_config.rb
New collection to map. 
Local transform and load in dev.
n/a
> Map Laussane IAS

- traject_configs/lausanne_ias_config.rb
Thumbnail url pattern changed on provider site.
Local transform, load in dev
N/A
> update palmyra mapping

- traject_configs/numismatic_csv_config.rb
Re-harvested ANS data
Local transform and load in dev
n/a
> remap ans data

- lib/macros/walters.rb
Get larger thumbs
local transform and load in dev
n/a
> larger walters thumbs

- config/metadata_mapping.json
- lib/translation_maps/getty_aat_materials.yaml
- lib/translation_maps/getty_aat_materials_to_ar.yaml
- lib/translation_maps/object_has_types.yaml
- lib/translation_maps/periodo.yaml
- lib/translation_maps/spatial.yaml
- lib/translation_maps/spatial_to_ar.yaml
- lib/translation_maps/temporal.yaml
- lib/translation_maps/temporal_to_ar.yaml
- lib/translation_maps/types.yaml
- traject_configs/yale_babylonian_config.rb
new dataset harvested
local transform and load in dev
n/a
> yale babylon mapping

- lib/translation_maps/temporal_ar_from_en.yaml
- lib/translation_maps/temporal_from_contributor.yaml
- traject_configs/yale_babylonian_config.rb
to update the temporal translation maps
n/a
> update temporal maps and config

- lib/controlled_vocabularies/edm_rights_en.yaml
- lib/controlled_vocabularies/edm_type_en.yaml
- lib/controlled_vocabularies/getty_aat_material_en.yaml
- lib/controlled_vocabularies/has_type_en.yaml
- lib/controlled_vocabularies/spatial_en.yaml
- lib/controlled_vocabularies/temporal_en.yaml
Adds English controlled vocabularies per https://github.com/sul-dlss/dlme-transform/issues/706. Still need Arabic values, unsure about whether language is necessary.
Manual inspection
n/a
> add controlled vocabularies

- traject_configs/princeton_movie_config.rb
- traject_configs/princeton_mss_config.rb
To fix known errors in the mapping.
n/a
> update princeton configs

- .rubocop.yml
- lib/macros/each_record.rb
- spec/lib/traject/macros/each_record_spec.rb
closes #677
* unit testing
* manual testing on laptop:
```sh
dlme-transform % exe/transform -w # i had only the aims data in my data dir, and i duplicated the title on the record in aims-9.xml
...snip...
W, [2021-07-15T17:52:11.129363 #24248]  WARN -- : traject_configs/aims_config.rb: key=cho_title; values=["Entretien avec Dr. Khadija Mohsen-Finan sur son dernier livre : Les Dissidents du Maghreb depuis les Independences", "Entretien avec Dr. Khadija Mohsen-Finan sur son dernier livre : Les Dissidents du Maghreb depuis les Independences"]; values array contains duplicates.  Check source data and/or traject config for errors.
{"cho_title":{"none":["Entretien avec Dr. Khadija Mohsen-Finan sur son dernier livre : Les Dissidents du Maghreb depuis les …
```
> prevent IR arrays from having duplicate values, warn if dupes are detected

- traject_configs/texas_tech_config.rb
Clean up Texas Tech mapping
local transform and load in dev
n/a
> update texas tech mapping

- traject_configs/princeton_mss_config.rb
The resource urls changes since last harvest
Local transform and load in dev
n/a
> update agg_is_shown_at urls

- README.md
> Adopt an easier release process

- traject_configs/shahre_farang_arabic_config.rb
- traject_configs/shahre_farang_english_config.rb
- traject_configs/shahre_farang_persian_config.rb
Fixes some errors in the config.
Local transform.
n/a
> update shahre farang mapping

- traject_configs/auc_oai_kraus_meyerhof_config.rb
- traject_configs/bnf_ideo_config.rb
- traject_configs/bnf_ifao_config.rb
> add missing lang keys

- lib/macros/title_extraction.rb
- spec/lib/traject/macros/title_extraction_spec.rb
- traject_configs/bodleian_arabic_config.rb
Some Bodleian records didn't have a title in the raw record
n/a
> fix Bodleian title extraction, add macro and tests

- spec/lib/traject/macros/title_extraction_spec.rb
address https://github.com/sul-dlss/dlme-transform/pull/770/files#r678647830
unit tests
n/a
> remove unused let vars

- README.md
Update documentation to link to a more recent example of a dlme-transform PR in README for dependency updates that matches the documentation
> Update dlme-transform PR example

- lib/macros/each_record.rb
- spec/lib/traject/macros/each_record_spec.rb
FIXES #679 
Adds unit test
n/a
1.  [x]  Fail and log to screen in debug mode
> Handling HTML tag in values

- lib/translation_maps/getty_aat_material_ar_from_en.yaml
- lib/translation_maps/has_type_ar_from_en.yaml
- lib/translation_maps/spatial_ar_from_en.yaml
- lib/translation_maps/temporal_ar_from_en.yaml
Captures the work in #779, #780, #781, and #782
> Update QNL provided translations

- invoke.sh
> Properly capture debug writer flag in invoke entrypoint

- README.md
> Update documentation about deployment

- README.md
> Typo in docker build command

- lib/translation_maps/temporal_ar_from_en.yaml
- traject_configs/yale_babylonian_config.rb
Add a new collection
local transform and load in dev
n/a
> yale update

- traject_configs/loc_abdul_hamid_ii_books_config.rb
Fixes a bug that should not have been merged.
n/a
> Fix lang code error that somehow got merged

- traject_configs/template_config.rb
We will have a new person learning the data mapping process and possibly others in the future. This will simplify the onboarding process and hopefully, reduce errors.
n/a
n/a
> Template config

- config/metadata_mapping.json
- traject_configs/aub_aco_config_csv.rb
- traject_configs/aub_aladab_config_csv.rb
- traject_configs/aub_poha_config_csv.rb
- traject_configs/aub_postcards_config_csv.rb
- traject_configs/aub_posters_config_csv.rb
- traject_configs/aub_travelbooks_config_csv.rb
Automate bodleian and bring config up to latest standards for mapping collection fields
n/a
> move bodleian to airflow

- traject_configs/ssm_iiif_config.rb
Fixes a mapping error
load in dev
n/a
> fix mapping error

- config/metadata_mapping.json
- traject_configs/texas_tech_config_csv.rb
> add csv config for texas tech

- config/metadata_mapping.json
- traject_configs/aims_config.rb
> move AIMS confic to csv

- traject_configs/aub_postcards_config_csv.rb
- traject_configs/aub_posters_config_csv.rb
- traject_configs/aub_travelbooks_config_csv.rb
fixes required lang tag errors
n/a
> fix traject errors

- config/metadata_mapping.json
This may be overwritten with @jacobthill in progress work, but I'd like to get this updated before this evening for the overnice harvest runs.
> Remove unused AUC config

- lib/translation_maps/agg_collection_ar_from_en.yaml
- lib/translation_maps/agg_collection_from_provider_id.yaml
- lib/translation_maps/edm_rights_from_contributor.yaml
- traject_configs/harvard_islamic_heritage_project.rb
- traject_configs/qnl.rb
> add qnl and harvard ihp

- lib/translation_maps/lang_ar_from_en.yaml
- lib/translation_maps/lang_from_downcased.yaml
- traject_configs/csic.rb
- traject_configs/harvard_islamic_heritage_project.rb
- traject_configs/sakip_sabanci_museum.rb
- fix traject errors surfaced in airflow
- local transform
- n/a
> fix some transform errors

- traject_configs/cambridge_genizah.rb
- traject_configs/cambridge_hebrew.rb
- traject_configs/cambridge_islamic.rb
- traject_configs/princeton.rb
- traject_configs/qnl.rb
- traject_configs/sakip_sabanci_museum.rb
- traject_configs/shahre_farang.rb
> add missing source file

- traject_configs/princeton.rb
- traject_configs/sakip_sabanci_museum.rb
> fix urls for princeton and ssm

- traject_configs/qnl.rb
Fix some transform errors found during QA
n/a
> Revise QNL traject config

- README.md
README updates to remove AWS specific information and add instructions for copying data to the stage server.
> Update readme to remove S3 copy commands

- config/metadata_mapping.json
- lib/macros/aub.rb
- lib/translation_maps/agg_collection_ar_from_en.yaml
- lib/translation_maps/agg_collection_from_provider_id.yaml
- lib/translation_maps/edm_type_from_provider.yaml
- traject_configs/aub_poha.rb
Somehow AUBs POHA config was removed. This PR puts it back and revises it.
Local transform and load in stage.
n/a
> Revise AUB mapping

- config/metadata_mapping.json
- lib/macros/path_to_file.rb
- lib/translation_maps/has_type_from_collection.yaml
- traject_configs/aub.rb
Fixes some issues in AUB transform
local transform and load in stage
n/a
> Revise AUB

- traject_configs/qnl.rb
> fix qnl mapping errors

- config/metadata_mapping.json
- lib/translation_maps/lang_ar_from_en.yaml
- lib/translation_maps/lang_from_downcased.yaml
- lib/translation_maps/lang_from_errors.yaml
- traject_configs/koch.rb
> Add new data provider

- traject_configs/koch.rb
> more mapping corrections

- traject_configs/qnl.rb
Missing QNL rights statement in English
n/a
> add qnl English rights

- config/metadata_mapping.json
- lib/macros/newcastle.rb
- lib/translation_maps/agg_collection_ar_from_en.yaml
- lib/translation_maps/agg_collection_from_provider_id.yaml
- spec/lib/traject/macros/newcastle_spec.rb
- traject_configs/newcastle.rb
> add newcastle mapping

- config/metadata_mapping.json
To fix some mapping errors
n/a
> fix data mapping errors

- lib/contracts/cho.rb
- lib/macros/prepend.rb
- lib/macros/walters.rb
- spec/lib/contracts/cho_spec.rb
- spec/lib/traject/macros/prepend_spec.rb
- spec/lib/traject/macros/walters_spec.rb
- traject_configs/walters.rb
We are getting Walters data in a new way.
Local transform.
n/a
> fix walters mapping for new data

- config/metadata_mapping.json
The traject paths in the airflow catalog changed.
n/a
> config path changes

- lib/macros/walters.rb
- traject_configs/walters.rb
Fixes an error in the collection-id field, removes creator (the values were ids that seemed to represent museum curators), and fixes thumbnail ids with blanks
n/a
> minor changes to walters config and macro

- lib/macros/normalize_language.rb
- traject_configs/newcastle.rb
Newcastle is a new collection
Loca transform
n/a
> Revise newcastle mapping

- traject_configs/loc.rb
The file path changed causing an error in the collection id field.
n/a
> fix loc collection id

- config/metadata_mapping.json
- lib/macros/language_extraction.rb
- lib/translation_maps/country_en_to_ar.yaml
- lib/translation_maps/data_provider_ar_from_en.yaml
- lib/translation_maps/data_provider_to_country.yaml
- lib/translation_maps/type_from_loc.yaml
- traject_configs/ucla_armenian.rb
- traject_configs/ucla_iiif.rb
- traject_configs/ucla_iiif_v3.rb
- traject_configs/ucla_no_preview.rb
Moved UCLA harvest to oai_dpla
n/a
> reivse ucla collections after moving to oai_dpla

- traject_configs/openiti.rb
> revise kitab-openiti config

- lib/translation_maps/has_type_ar_from_en.yaml
- traject_configs/openiti.rb
Adjusts mapping based on provider feedback.
n/a
> fix openiti mapping

- lib/macros/open_iti.rb
- spec/fixtures/source_data/openiti/data_first_10.json
- spec/lib/traject/macros/open_iti_spec.rb
> fix ocr field issue

- lib/translation_maps/agg_collection_ar_from_en.yaml
- lib/translation_maps/agg_collection_from_provider_id.yaml
> add collection to openiti

- Dockerfile
- Gemfile.lock
> Update the Dockerfile dependencies

- lib/translation_maps/agg_collection_ar_from_en.yaml
- lib/translation_maps/agg_collection_from_provider_id.yaml
- traject_configs/princeton.rb
Princeton transform was failing in Airflow.
Local transform.
n/a
> update Princeton traject

- lib/macros/prepend.rb
- lib/translation_maps/lang_ar_from_en.yaml
- lib/translation_maps/lang_from_downcased.yaml
- traject_configs/penn_museum.rb
Noticed missing fields when loading Penn Museum. The traject config was out of date.
n/a
> update Penn Museum mapping

- traject_configs/auc.rb
> fix auc agg_is_shown_at

- traject_configs/auc.rb
> add more type fields

- lib/macros/normalize_type.rb
- lib/translation_maps/has_type_from_contributor.yaml
- spec/lib/traject/macros/normalize_type_spec.rb
- traject_configs/ucla_armenian.rb
- traject_configs/ucla_iiif.rb
- traject_configs/ucla_no_preview.rb
> UCLA wasn't getting edm or has type values

- lib/translation_maps/lang_ar_from_en.yaml
- lib/translation_maps/lang_from_downcased.yaml
- traject_configs/leiden.rb
- traject_configs/ucla_armenian.rb
- traject_configs/ucla_iiif.rb
- traject_configs/ucla_no_preview.rb
> update Leiden mapping

- .circleci/config.yml
- .rubocop.yml
- Dockerfile
- Gemfile
- Gemfile.lock
> Upgrade to ruby 3.4.1

- traject_configs/newcastle.rb
> fix thumbnail url

- lib/translation_maps/lang_from_french.yaml
- lib/translation_maps/lang_from_iso_639-2.yaml
- traject_configs/bnf.rb
> Update BnF config

- config/metadata_mapping.json
- lib/translation_maps/agg_collection_ar_from_en.yaml
- lib/translation_maps/agg_collection_from_provider_id.yaml
- traject_configs/bnf.rb
> Update config per request of BnF
